version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: wow-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trinity
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  wow-build:
    build: .
    image: wow-lk-3.3.5

  authserver:
    image: wow-lk-3.3.5
    container_name: wow-auth
    depends_on:
      - db
    restart: always
    volumes:
      - ${PWD}/etc:/app/etc
      - ${PWD}/data:/app/data
    working_dir: /app
    command:
      - sh
      - -c
      - |
        until mysql -h db -u root -ptrinity -e "SELECT 1" >/dev/null 2>&1; do
          sleep 2
        done
        ./bin/authserver
    ports:
      - "3724:3724"

  worldserver:
    image: wow-lk-3.3.5
    container_name: wow-world
    depends_on:
      - db
      - authserver
    restart: always
    volumes:
      - ${PWD}/etc:/app/etc
      - ${PWD}/data:/app/data
    working_dir: /app
    stdin_open: true
    tty: true
    command:
      - sh
      - -c
      - |
        until mysql -h db -u root -ptrinity -e "SELECT 1" >/dev/null 2>&1; do
          sleep 2
        done
        ./bin/worldserver
    ports:
      - "8085:8085"

volumes:
  db_data: